### ISSUE TITLE
Ubuntu 15.10 (Wily) is not LTS and reached end of life in July 2016

### ISSUE THREAD

**Issue by danwad** [JetBrains/teamcity-docker-minimal-agent#1]
Ubuntu 15.10 was only supported for 9 months as it was not a long term support release.

It has reached end of life. See https://lists.ubuntu.com/archives/ubuntu-announce/2016-July/000210.html

Are you expecting to update the base image to an Ubuntu version with a longer support life such as Ubuntu 16.04.1 LTS which is supported until April 2021?

We are having issues installing some of our build dependencies on this version of Ubuntu.

**Comment by staffan-einarsson** [comment]
This is affecting us as well.

Since you are unable to publish the underlying Dockerfile(s) that specify which OS distro to use, it would be prudent to at least base it on an LTS release.

**Comment by VladRassokhin** [comment]
Next time TeamCity releases (10.0.5) docker images would be based on `ubuntu:xenial` image.

**Comment by staffan-einarsson** [comment]
@VladRassokhin Thanks for the heads-up. This is good news.

**Comment by VladRassokhin** [comment]
@staffan-einarsson We've just released 10.0.5 with Ubuntu 16.04 as base image.
