### ISSUE TITLE
jetbrains/teamcity-base does not exist

### ISSUE THREAD

**Issue by andrewsav-datacom** [JetBrains/teamcity-docker-minimal-agent#13]
readme.md says:

>>Pull our base image and re-tag it `docker pull jetbrains/teamcity-base`

When you run this command you get the following error:

```
Using default tag: latest
Error response from daemon: pull access denied for jetbrains/teamcity-base, repository does not exist or may require 'docker login'
```

**Comment by dtretyakov** [comment]
@andrewsav-datacom, thanks for reporting it. Instruction was updated:
https://github.com/JetBrains/teamcity-docker-minimal-agent
