### ISSUE TITLE
Agent cannot connect to server over HTTPS using Let's Encrypt Certificate

### ISSUE THREAD

**Issue by sjawhar** [JetBrains/teamcity-docker-minimal-agent#15]
Using the 2017.1.4 version of the TeamCity Agent image, the agent fails while trying to connect to the TeamCity server over HTTPS when using a valid Let's Encrypt certificate. The error given is:
> sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by dtretyakov** [comment]
@sjawhar, it's quite strange since in the images used Java 1.8.0_131 where [exists Let's Encrypt certificate](https://letsencrypt.org/docs/certificate-compatibility/):
```
docker run --rm jetbrains/teamcity-minimal-agent:2017.1.4 java -version
```

**Comment by dtretyakov** [comment]
Closing as obsolete.
