### ISSUE TITLE
Allow configuration of custom properties

### ISSUE THREAD

**Issue by agross** [JetBrains/teamcity-docker-minimal-agent#19]
The scripts already supports configuring the server URL and agent name. As I understand the output of `/opt/buildagent/bin/agent.sh configure --help` one could add custom properties as well, perhaps prefixed with `CONF_`.

E.g.

```
docker run --env CONF_foo.bar.baz=42 jetbrains/teamcity-docker-minimal-agent
```

will add `foo.bar.baz = 42` to `buildAgent.properties`.

This is useful if you start from the minimal agent and on some agents you e.g. install rsync. Then you can discern rsync-enabled agents by adding an `--env` parameter like above.

**Comment by VladRassokhin** [comment]
I've just merged #20 which adds support for 'AGENT_OPTS' variable. Hopefully it's what is needed.
