### ISSUE TITLE
How to install Docker Dameon in Minimal Setup?

### ISSUE THREAD

**Issue by meshfields** [JetBrains/teamcity-docker-minimal-agent#24]
I am struggling to give my helm chart the correct parameters (args) 
```
"-v", "docker_volumes:/var/lib/docker", "--privileged"
```
on its way since it expect a CMD from me too. I can't find the Entrypoint in the full agent image, therefore I am turning to the minimal image here in order to get the docker daemon up and running myself. Can you provide a few hints how to get it running in the minimal agent?

**Comment by kir** [comment]
The minimal agent does not contain docker, and cannot be used to run docker build steps. You should be using full agent image instead.
