### ISSUE TITLE
Update Ubuntu base image to newer JDK version

### ISSUE THREAD

**Issue by azabost** [JetBrains/teamcity-docker-minimal-agent#36]
Hi. I would like to suggest updating the base Ubuntu image. As far as I can see, the Ubuntu image is built on top of `adoptopenjdk/openjdk8:x86_64-ubuntu-jdk8u192-b12` which could be updated to something newer, like `adoptopenjdk/openjdk8:x86_64-ubuntu-jdk8u222-b10`.

The idea comes from an observation that Android application builds performed on `jetbrains/teamcity-agent` (which is effectively based on this `teamcity-minimal-agent` image) report the following warnings:

```
warning: Current JDK version 1.8.0_192-b12 has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.
[kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).
```

When I checked the JetBrains Runtime version distributed with the latest stable version of Android Studio, it was:

```
openjdk version "1.8.0_202-release"
OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
```

What do you think?

**Comment by kir** [comment]
TeamCity 2019.1.4 will use `adoptopenjdk:8u222-b10-jdk-hotspot` (to be released this week)

**Comment by azabost** [comment]
@kir I have just verified that the issue persists in 2019.1.4, 2019.1.5 and 2019.2. Can we reopen it, please?

Also, there is something about the Java versions in those images that I don't understand.
By experimenting with all these images:

* teamcity-minimal-agent:2019.1.4
* teamcity-minimal-agent:2019.1.5
* teamcity-minimal-agent:2019.2
* adoptopenjdk/openjdk8:x86_64-ubuntu-jdk8u222-b10

I was able to confirm that the **only** image that seems to fix the issue (the warnings are not reported) is `adoptopenjdk/openjdk8:x86_64-ubuntu-jdk8u222-b10` despite that it reports the same Java version as 2019.1.4 and 2019.1.5 😵🤷‍♂️. So the fix in 789d1b9cf9f6b8c948054cc6111eb5f957d1ca38 also didn't help.

2019.1.4, 2019.1.5 and `adoptopenjdk/openjdk8:x86_64-ubuntu-jdk8u222-b10` report the following `java -version`:
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
```

2019.2 reports this:
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment Corretto-8.232.09.1 (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM Corretto-8.232.09.1 (build 25.232-b09, mixed mode)
```

**Comment by kir** [comment]
Hello @azabost ,

You write that "I have just verified that the issue persists" - you're talking about reported warning, correct? How the message looks for the 2019.2 exactly?

Thanks,

**Comment by azabost** [comment]
Yes, I'm talking about the warnings I mentioned in the first post. In 2019.2 I can see the following:

```
w: warning: Current JDK version 1.8.0_232-b09 has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.
w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).
```

Additionally, I must admit I was wrong about the benefit of using `adoptopenjdk/openjdk8:x86_64-ubuntu-jdk8u222-b10`. My mistake was probably caused by not triggering the clean build. When I clean one of the modules using kapt in my project, let's say `:common:clean :common:kaptDebugKotlin`, I can see the same warning again. I'm sorry for misleading you.

**Comment by kir** [comment]
@azabost , thanks for the clarification. I'm afraid so far we don't have plans to provide build agent docker image with Java 11 out of the box, I'd suggest you build a custom image, install a newer Java version there, and use it. You can just tweak https://github.com/JetBrains/teamcity-docker-minimal-agent/blob/master/ubuntu/Dockerfile file and download Java 11 there, or download and install it separately, using existing teamcity-minimal-agent as a base for your image.

**Comment by azabost** [comment]
Understood. Thanks for your assistance 👍
