### ISSUE TITLE
Running TC-agent on a windows docker machine

### ISSUE THREAD

**Issue by abergs** [JetBrains/teamcity-docker-minimal-agent#4]
Hi!

I've got a windowsservercore machine running tc-agent but I'm having trouble keeping the container alive due to Agent upgrade and restart.

I would need a start script (powershell or bat) that correctly keeps the container running and restarts a crashed agent.

Could you help me with this?

My dockerfile runs "bin/agent.bat start" which immediately returns 0 because it spawns a new shell.
I tweaked agent.bat to run `start /wait` on the JAVA process.

However, it still shuts down for upgrades. Can I disable this upgrade or would it be possible to write a script that correctly runs the whole upgrade process?

**Comment by VladRassokhin** [comment]
Hi @abergs 
Cannot say much about batch scripts, but for linux we use next approach:
 * Run agent in background
 * Trap all interrupts like Ctrl+C to execute `agent.sh stop`
 * Continuously tail log file

Well, that's the logic of [run-agent.sh](https://github.com/JetBrains/teamcity-docker-minimal-agent/blob/master/run-agent.sh)
You may try to implement something similar with batch or PowerShell

**Comment by VladRassokhin** [comment]
Probably it's fixed in #7 
@abergs could you please try latest image?

**Comment by dtretyakov** [comment]
@abergs, now we have windows docker images, so you could try to use them.

**Comment by abergs** [comment]
Thank you @dtretyakov will test them!
