### ISSUE TITLE
agent is not shutting down cleanly

### ISSUE THREAD

**Issue by crafty78** [JetBrains/teamcity-docker-minimal-agent#6]
the run-agent.sh is trying to trap signals to shutdown the agent cleanly but never receives them as run-agent.sh is spawned at the end run-services.sh, so is not running as pid 1 and never receives any signals. 

I tested this and fixed locally by replacing the last line of run-services.sh with:

 `exec /run-agent.sh`

and it then works as expected. I can submit a pr if agreed this is correct approach?

**Comment by VladRassokhin** [comment]
I'd investigate issue tomorrow.
Do you use latest version (10.0.5) of image? If so, feel free to create pull-request.
